const activitesList = [
    { name: "kayaking", type: "sport, day-out" },
    { name: "Durdle Door Hike", type: "day-out" },
    { name: "Spa Day", type: "day-out" },
    { name: "Indoor Badminton", type: "sport" },
    { name: "Tennis", type: "sport" },
    { name: "The Foo", type: "Games" },
    { name: "Bowling & Arcade (Reading)", type: "day-out" },
    { name: "Indoor Skiing", type: "sport, day-out" },
    { name: "Jigsaw couples competition", type: "day-out" },
    { name: "Pottery", type: "day-out" },
    { name: "Foraging", type: "day-out" },
    { name: "Midnight at Spitalfields Market", type: "day-out" },
    { name: "Fruit picking", type: "day-out" },
    { name: "Theme park", type: "day-out" },
];
