const restaurantList = [
    {
        name: "The Bap",
        city: "Reading",
        type: "Meal",
        continentalCuisine: "Asian",
        countryCuisine: "Korean",
    },
    {
        name: "Norma",
        city: "London",
        type: "Meal",
        continentalCuisine: "European",
        countryCuisine: "Italian",
    },
    {
        name: "Dishoom",
        city: "London",
        type: "Meal",
        continentalCuisine: "Asian",
        countryCuisine: "Indian",
    },
    {
        name: "Angry Crab",
        city: "London",
        type: "Meal",
        continentalCuisine: "Americas",
        countryCuisine: "USA",
    },
    {
        name: "Sweeney & Todd",
        city: "Reading",
        type: "Meal",
        continentalCuisine: "European",
        countryCuisine: "British",
    },
    {
        name: "Pink Berry",
        city: "London",
        type: "Dessert",
        continentalCuisine: "Americas",
        countryCuisine: "USA",
    },
    {
        name: "Charm Thai",
        city: "Bath",
        type: "Meal",
        continentalCuisine: "Asian",
        countryCuisine: "Thai",
    },
    {
        name: "Yum Yum Thai",
        city: "Bath",
        type: "Meal",
        continentalCuisine: "Asian",
        countryCuisine: "Thai",
    },
    {
        name: "The Scallop Shell",
        city: "Bath",
        type: "Meal",
        continentalCuisine: "European",
        countryCuisine: "British",
    },
    {
        name: "Pink Berry",
        city: "London",
        type: "Dessert",
        continentalCuisine: "Americas",
        countryCuisine: "USA",
    },
];
